name: "Export project"
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GODOT_VERSION: 4.3

jobs:
  check-gh-pages:
    name: Check if GitHub Pages is enabled
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh api "repos/${{ github.repository }}/pages" | jq --exit-status '.build_type == "workflow"'
          then
              echo "enabled=true" >> "$GITHUB_OUTPUT"
          else
              echo "# Not published to GitHub Pages" >> "$GITHUB_STEP_SUMMARY"
              echo "" >> "$GITHUB_STEP_SUMMARY"
              echo "Check that Pages is enabled, with the source set to GitHub Actions, in the" >> "$GITHUB_STEP_SUMMARY"
              echo "[repository settings](https://github.com/${{ github.repository }}/settings/pages)." >> "$GITHUB_STEP_SUMMARY"
          fi
    outputs:
      enabled: ${{ steps.check.outputs.enabled }}

  build-web:
    name: Build for web
    needs:
      - check-gh-pages
    if: ${{ needs.check-gh-pages.outputs.enabled }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" ./build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web
          path: build/web

  publish-gh-pages:
    name: Publish to GitHub Pages
    needs:
      - build-web
    runs-on: ubuntu-latest
    steps:
      - id: deploy-to-gh-pages
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: web

      - name: Show URL in summary
        if: ${{ steps.deploy-to-gh-pages.outcome == 'success' }}
        run: |
          echo "Game published to: <${{ steps.deploy-to-gh-pages.outputs.page_url }}>" >>$GITHUB_STEP_SUMMARY
